name: PAM JWT
on:
  push: {}
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y libpam0g-dev

      - name: Build .so library
        run: make build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pam_jwt.so
